---
- name: disks
  hosts: redhat
  become: true
  gather_facts: false
  tasks:
    - name: create disk file
      command:
        cmd: fallocate -l 1G /root/disk1
        creates: /root/disk1
    - name: link with losetup
      command:
        cmd: losetup /dev/loop10 /root/disk1
        creates: /dev/loop10

