---
- name: disks
  hosts: redhat
  become: true
  gather_facts: false
  tasks:
    - name: create disk file
      command:
        cmd: fallocate -l 1G /root/disk1
        creates: /root/disk1
    - name: link with losetup
      command:
        cmd: losetup /dev/loop10 /root/disk1
        creates: /dev/loop10
    - name: partition
      parted:
        device: /dev/loop10
        number: 1
        state: present
    - name: filesystem
      filesystem:
        device: /dev/loop10p1
        fstype: xfs
    - name: create mount point
      file:
        path: /data
        state: directory
        owner: root
        group: wheel
        mode: '3770'
    - name: mount fs
      mount:
        path: /data
        src: /dev/loop10p1
        state: mounted
        fstype: xfs

