---
- name: manage apache httpd
  hosts: redhat
  become: true
  gather_facts: false
  tasks:
    - name: install apache web server
      package:
        name: httpd
        state: present
    - name: deliver content
      copy:
        dest: /var/www/html/
        src: "{{ lookup('env', 'HOME') }}/web/"
    - name: start and enable service
      service:
        name: httpd
        state: started
        enabled: true
