- name: Create and Manage Users
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create User Account
      user:
        name: fred
        state: present
        shell: /bin/bash
