- name: Manage Apache Web Server
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install the Apache Web Server Package
      package:
        name: "{{ apache_pkg }}"
        state: present

    - name: Server Tokens
      lineinfile:
        path: "{{ apache_conf }}"
        regexp: "^ServerTokens .*$"
        insertafter: "^ServerRoot"
        line: ServerTokens OS
      notify: RestartApache

    - name: add web content
      copy:
        src: www/
        dest: /var/www/html/

    - name: Start and enable Apache web server
      service:
        name: "{{ apache_svc }}"
        state: started
        enabled: true

  handlers:
    - name: RestartApache
      service:
        name: "{{ apache_svc }}"
        state: restarted