- name: Manage Firewalld
  hosts: all
  become: true
  gather_facts: false
  tasks:
    -
    - name: Ensure that UFW Firewall is not installed
      package:
        name: ufw
        state: absent

    - name: Ensure Firewalld Firewall is installed
      package:
        name: firewalld
        state: present

    - name: Ensure Firewalld Firewall is enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Automate searching for bad logins
      cron:
        name: ssh_root_attempts
        minute: 0
        user: root
        cron_file: ssh_root_attempts
        state: present
        job: journalctl -u ssh -g "Failed password for root" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u > ~tux/server

    - name: Process Disallowed List
      firewalld:
        state: enabled
        zone: block
        permanent: true
        immediate: true
        source: "{{ item }}"
      loop: "{{ lookup('file', '/home/tux/server').split('\n') }}"
